### PR TITLE
Update users.yml

### PR DESCRIPTION
**Pull request by poweredgenl**
add user handle PP Kurstjens/NetOne

### CODE REVIEW

**Comment by poweredgenl** [comment]
i see on the website - my name / some other info is not yet populated. Slight nudge if it can be added... no rush :-)

**Comment by casdr** [comment]
Ah, there's a small typo: full_**m**ame

**Comment by casdr** [comment]
Fixed! :-)

**Comment by poweredgenl** [comment]
thanks !

**Pull request merged**
