### PR TITLE
Improving index.html with search parameter in url and auto-adjusted url

### PR DESCRIPTION
**Pull request by martijn-gr**
Adding search capability to be stored in the URL.

### CODE REVIEW

**Comment by casdr** [comment]
What happens if ?q isn't set?

**Comment by martijn-gr** [comment]
> What happens if ?q isn't set?

Full table is shown,

Same when "q="  is set

**Comment by casdr** [comment]
Wouldn't this cause an error? As you're getting the 'q' value directly at https://github.com/casdr/nlnogbook/pull/97/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR138

**Comment by martijn-gr** [comment]
> Wouldn't this cause an error? As you're getting the 'q' value directly at https://github.com/casdr/nlnogbook/pull/97/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR138

Well, good question.

q is pulled from the url to be used in the search box and search the table;
If q is not set it will not be available and the query var will initialize empty.
If q is set but empty it will also initialize empty.
The search will be performed.
This is a one-time action which only happens on the document ready event.

Further on each keyup event of the searchbox a browser history state push is launched, requesting to update the browser history and show a new url in the address bar. As there is no page redirect, it will not fire the doument.ready event.

This should be save in every way.
No errors are thrown in Chrome.  

Functionality can be tested here:
https://netwerkjongens.nl/~martijn/nlnogbook/?q=casdr
https://netwerkjongens.nl/~martijn/nlnogbook/?q=
https://netwerkjongens.nl/~martijn/nlnogbook/?

**Pull request merged**
